# Generated by Django 5.2.17 on 2026-09-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_attempt_reminder_sent_at_question_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='adaptive_question_count',
            field=models.PositiveIntegerField(default=10, help_text="Used only when selection mode is Adaptive: how many questions to pull from the category pool each attempt, weighted toward the student's weaker difficulty levels."),
        ),
        migrations.AddField(
            model_name='quiz',
            name='selection_mode',
            field=models.CharField(choices=[('fixed', 'Fixed question set'), ('adaptive', 'Adaptive (auto-selected per student)')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='quizzes.tag'),
        ),
    ]
